services:
  - type: web
    name: my-django-genai-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false  # Set this value in Render Dashboard
      - key: DEBUG
        value: "False"
