services:
  - type: web
    name: my-django-genai-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python nltk_setup.py
    startCommand: gunicorn MyProject.wsgi:application
    envVars:
      - key: GROQ_API_KEY
        sync: false
