# services:
#   - type: web
#     name: my-django-genai-app
#     env: python
#     buildCommand: |
#       pip install -r requirements.txt
#       python nltk_setup.py
#     startCommand: gunicorn MyProject.wsgi:application --bind 0.0.0.0:$PORT --timeout 90
#     envVars:
#       - key: GROQ_API_KEY
#         sync: false
# #