/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/orders'
    | '/profile'
    | '/search'
    | '/signin'
    | '/signup'
    | '/books/$bookId'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/orders'
    | '/profile'
    | '/search'
    | '/signin'
    | '/signup'
    | '/books/$bookId'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/orders'
    | '/profile'
    | '/search'
    | '/signin'
    | '/signup'
    | '/books/$bookId'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
