# Generated by Django 5.1.2 on 2025-04-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(
                default="",
                help_text="Comma-separated tags for user interests",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="purchased_products",
            field=models.ManyToManyField(related_name="buyers", to="user.product"),
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_logs",
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
