# Generated by Django 5.1.8 on 2025-04-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF file for the product",
                null=True,
                upload_to="static/pdfs/",
            ),
        ),
    ]
