# Generated by Django 5.1.8 on 2025-04-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_product_dislikes_product_likes_productinteraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBookInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("purchase", "Purchase"),
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("review", "Review"),
                            ("search", "Search"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "book"], name="user_userbo_user_id_7ed291_idx"
                    ),
                    models.Index(
                        fields=["interaction_type"],
                        name="user_userbo_interac_707307_idx",
                    ),
                ],
            },
        ),
    ]
