# Generated by Django 5.1.8 on 2025-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_userbookinteraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interests",
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="user.interesttag"),
        ),
    ]
