# Generated by Django 5.1.8 on 2025-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_interesttag_alter_profile_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="user.interesttag"),
        ),
    ]
