# Generated by Django 5.1.8 on 2025-05-23 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_userinteraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("click", "Click"),
                    ("rating", "Rating"),
                    ("add_to_cart", "Add to Cart"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="userinteraction",
            unique_together={("user", "product", "interaction_type")},
        ),
    ]
