# Generated by Django 5.1.8 on 2025-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_userinteraction_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="disliked_users",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_products", to="user.profile"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_products", to="user.profile"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
