# Generated by Django 5.1.8 on 2025-06-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_userinteraction_interaction_type_userinterest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="user.interesttag"),
        ),
        migrations.DeleteModel(
            name="UserInterest",
        ),
    ]
