"""initial schema

Revision ID: 2f63606ee597
Revises: 
Create Date: 2026-10-05 14:52:42.734706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f63606ee597'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_addtocart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('cdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(length=40), nullable=False),
    sa.Column('cpic', sa.String(length=500), nullable=False),
    sa.Column('cdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=600), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interesttag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('odate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('passwd', sa.String(length=100), nullable=False),
    sa.Column('ppic', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ppic', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('hardcover', sa.String(length=50), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('tprice', sa.Float(), nullable=False),
    sa.Column('disprice', sa.Float(), nullable=False),
    sa.Column('pdes', sa.Text(), nullable=False),
    sa.Column('pdate', sa.Date(), nullable=False),
    sa.Column('pdf', sa.String(length=500), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['user_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_product_category_id'), 'user_product', ['category_id'], unique=False)
    op.create_table('user_profile_interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=80), nullable=False),
    sa.Column('interesttag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesttag_id'], ['user_interesttag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_searchlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_searchlog_user_id'), 'user_searchlog', ['user_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('bucket', sa.String(length=63), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['user_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.email'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'path'),
    sa.UniqueConstraint('public_url')
    )
    op.create_index(op.f('ix_media_files_category_id'), 'media_files', ['category_id'], unique=False)
    op.create_index(op.f('ix_media_files_kind'), 'media_files', ['kind'], unique=False)
    op.create_index(op.f('ix_media_files_product_id'), 'media_files', ['product_id'], unique=False)
    op.create_index(op.f('ix_media_files_profile_id'), 'media_files', ['profile_id'], unique=False)
    op.create_table('user_product_disliked_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_product_liked_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_product_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('interesttag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesttag_id'], ['user_interesttag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile_purchased_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_review_product_id'), 'user_review', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_review_user_id'), 'user_review', ['user_id'], unique=False)
    op.create_table('user_userinteraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['user_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', 'interaction_type')
    )
    op.create_index(op.f('ix_user_userinteraction_product_id'), 'user_userinteraction', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_userinteraction_user_id'), 'user_userinteraction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userinteraction_user_id'), table_name='user_userinteraction')
    op.drop_index(op.f('ix_user_userinteraction_product_id'), table_name='user_userinteraction')
    op.drop_table('user_userinteraction')
    op.drop_index(op.f('ix_user_review_user_id'), table_name='user_review')
    op.drop_index(op.f('ix_user_review_product_id'), table_name='user_review')
    op.drop_table('user_review')
    op.drop_table('user_profile_purchased_products')
    op.drop_table('user_product_tags')
    op.drop_table('user_product_liked_users')
    op.drop_table('user_product_disliked_users')
    op.drop_index(op.f('ix_media_files_profile_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_product_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_kind'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_category_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_user_searchlog_user_id'), table_name='user_searchlog')
    op.drop_table('user_searchlog')
    op.drop_table('user_profile_interests')
    op.drop_index(op.f('ix_user_product_category_id'), table_name='user_product')
    op.drop_table('user_product')
    op.drop_table('user_profile')
    op.drop_table('user_order')
    op.drop_table('user_interesttag')
    op.drop_table('user_contact')
    op.drop_table('user_category')
    op.drop_table('user_addtocart')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
